# 使用更容易获取的基础镜像
FROM openjdk:21-slim AS builder

WORKDIR application
ARG JAR_FILE=application/build/libs/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

################################

FROM openjdk:21-slim
LABEL maintainer="johnniang <johnniang@foxmail.com>"
WORKDIR application

COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./

ENV JVM_OPTS="-Xmx256m -Xms256m" \
    HALO_WORK_DIR="C:/halo2" \
    SPRING_CONFIG_LOCATION="optional:classpath:/;optional:file:C:/halo2/" \
    TZ=Asia/Shanghai

EXPOSE 8090

ENTRYPOINT ["cmd", "/C", "java -Dreactor.schedulers.defaultBoundedElasticOnVirtualThreads=true %JVM_OPTS% org.springframework.boot.loader.launch.JarLauncher %*"]